services:
    mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - '27017:27017'
      volumes:
        - /Users/efo/data/db:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: Passw0rd
