services:
    mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - '27017:27017'
      volumes:
        - /<your>/<host>/<path>:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: <root_user>
        MONGO_INITDB_ROOT_PASSWORD: <pass>
